live_config_reload: true

env:
  TERM: xterm-256color

font:
  normal:
    family: "MesloLGL Nerd Font Mono"
    # style: Medium
  size: 20.0

window:
  opacity: 1
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: buttonless

# Copy on mouse selection
# https://github.com/alacritty/alacritty/issues/2768#issuecomment-526760816
selection:
  save_to_clipboard: true

key_bindings:
  - { key: Comma, mods: Command, chars: "\x02," }
  - { key: D, mods: Command, chars: "\x02K" }
  - { key: E, mods: Command, chars: "\x02\"" }
  - { key: E, mods: Command|Shift, chars: "\x02%" }
  - { key: F, mods: Command, chars: "\x02\x5b\x2f" }
  - { key: F, mods: Command|Shift, chars: "lfcd\n" }
  - { key: G, mods: Command, chars: "\x02g" }
  - { key: J, mods: Command, chars: "\x02\x54" }
  - { key: K, mods: Command, chars: "\x02s" }
  - { key: Key1, mods: Command, chars: "\x021" }
  - { key: Key2, mods: Command, chars: "\x022" }
  - { key: Key3, mods: Command, chars: "\x023" }
  - { key: Key4, mods: Command, chars: "\x024" }
  - { key: Key5, mods: Command, chars: "\x025" }
  - { key: Key6, mods: Command, chars: "\x026" }
  - { key: Key7, mods: Command, chars: "\x027" }
  - { key: Key8, mods: Command, chars: "\x028" }
  - { key: Key9, mods: Command, chars: "\x029" }
  - { key: L, mods: Command, chars: "\x02L" }
  - { key: LBracket, mods: Command, chars: "\x0f" }
  - { key: LBracket, mods: Command|Shift, chars: "\x02p" }
  - { key: O, mods: Command, chars: "\x02u" }
  - { key: P, mods: Command, chars: "\x02\x50" }
  - { key: P, mods: Command|Shift, chars: ":Telescope commands\n" }
  - { key: Period, mods: Command, chars: ":ZenMode\n" }
  - { key: Q, mods: Command, chars: ":q\n" }
  - { key: R, mods: Command, chars: "\x1b\x5b\x41\x0a" }
  - { key: RBracket, mods: Command, chars: "\x09" }
  - { key: RBracket, mods: Command|Shift, chars: "\x02n" }
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" }
  - { key: S, mods: Command|Shift, chars: ":wa\n" }
  - { key: Semicolon, mods: Command, chars: "\x02:" }
  - { key: T, mods: Command, chars: "\x02c" }
  - { key: W, mods: Command, chars: "\x02x" }
  - { key: Z, mods: Command, chars: "\x02z" }
