require('shamindras.plugins.impatient') -- impatient must be loaded first
require('shamindras.plugins-setup')
require('shamindras.core.options')
require('shamindras.core.keymaps')
require('shamindras.core.autocmds')
require('shamindras.plugins.catppuccin') -- catppuccin color theme
require('shamindras.core.colorscheme') -- load this after loading color theme
require('shamindras.plugins.comment')
require('shamindras.plugins.nvim-tree')
require('shamindras.plugins.lualine')
require('shamindras.plugins.telescope')
require('shamindras.plugins.nvim-cmp')
require('shamindras.plugins.lsp.mason')
require('shamindras.plugins.lsp.lspsaga')
require('shamindras.plugins.lsp.lspconfig')
require('shamindras.plugins.lsp.null-ls')
require('shamindras.plugins.autopairs')
require('shamindras.plugins.treesitter')
require('shamindras.plugins.tabout')
require('shamindras.plugins.gitsigns')
