# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"
truncation_length = 8
truncate_to_repo = false

[aws]
disabled = true

[cmd_duration]
disabled = true

[rlang]
disabled = true

[hostname]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust] 
disabled = true

[username]
disabled = true

