live_config_reload = true

[["keyboard.bindings"]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002\""
key = "E"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = "\u0002T"
key = "J"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002s"
key = "K"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002L"
key = "L"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[["keyboard.bindings"]]
chars = """
lazygit;clear;
"""
key = "G"
mods = "Command | Shift"

[["keyboard.bindings"]]
chars = """
nvim .;clear;
"""
key = "N"
mods = "Command | Shift"

[["keyboard.bindings"]]
chars = """
vifm .;clear;
"""
key = "V"
mods = "Command | Shift"

[["keyboard.bindings"]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = "\u0002u"
key = "O"
mods = "Command"

[["keyboard.bindings"]]
chars = """
:GoToFile
"""
key = "P"
mods = "Command"

[["keyboard.bindings"]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = """
\u001B[A
"""
key = "R"
mods = "Command"

[["keyboard.bindings"]]
chars = "\t"
key = "RBracket"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[["keyboard.bindings"]]
chars = """
:wa
"""
key = "S"
mods = "Command|Shift"

[["keyboard.bindings"]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002c"
key = "T"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002x"
key = "W"
mods = "Command"

[["keyboard.bindings"]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "MesloLGL Nerd Font Mono"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 3
y = 3

# import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.yml"]
