#!/usr/bin/env sh

# The following yabai config was mainly taken from Josh Medeski's setup
# source:
# https://github.com/joshmedeski/dotfiles/blob/f43577e695c9bfba1cbd9423a5ec731ba7e1f3fd/mackup/.yabairc
# Some additional configuration is taken from Julian Heng's setup as well
# source: https://github.com/julian-heng/yabai-config/blob/a3776dd27c32e02afecf3f2913c4ac9f65d29925/yabairc

# source: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xE02d74da
yabai -m config normal_window_border_color   0x00010101
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                15
yabai -m config window_gap                   15

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add app="^Alfred Preferences$" manage=off

echo "yabai configuration loaded.."
