gui:
  showIcons: true
  # use the mocha catpuccin theme
  # see: https://github.com/catppuccin/lazygit/tree/06f59293af3de63621f3de946f58e4fe3b60a8f0#usage
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"
